# *Multiple Linear Regression* 
General E.g for understanding 

In [1]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

let's handle NA value 

bedroom ka Median lelete chalo 

In [4]:
import math 

In [5]:
df['bedrooms'].median()
# df.bedrooms.median()

4.0

In [6]:
df.bedrooms.fillna(df['bedrooms'].median(),inplace=True)

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
lr = LinearRegression()

In [18]:
x = df.iloc[:,0:-1]
y = df['price']

In [48]:
# from sklearn.model_selection import train_test_split 
# x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [47]:
# x_train

In [49]:
# y_train

In [50]:
# x_test

In [51]:
# lr.predict(x_test)

In [52]:
# lr.score(x_test,y_test)

In [53]:
# y_test

In [10]:
df.iloc[:,0:-1]
# x =df.iloc[:,0:1] 
# y = df.iloc[:,-1]

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [11]:
lr.fit(df.iloc[:,0:-1],df['price'])

LinearRegression()

Qs -> 3k Area, 3 Bedroom , 40 years old

In [12]:
lr.predict([[3000,3,40]])

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [13]:
lr.predict([[3000,3,40]])

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [14]:
lr.coef_
# age negative isliye hai ki jaise Age badhta hai vaise price ghatta hai 

array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
lr.intercept_

221323.00186540408

In [1]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540408

498408.2515740241

Qs --> 2500 Area, 4 Bedrooms, 5 years old 

In [17]:
lr.predict([[2500,4,5]])

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])