# Need of Numpy 

Alag se array ka zarrurat kya hai jbh List hai Python mai tou ?
2008 & 2009 jbh aaya tha tbhi Matlab & R use krke ML krte theah. 
Because python slow tha tbhi sbh data type slow hai so python use nahi hota tha.
ML mai GBS of data pe kaam krte theah.
Tbh Numpy aagaya market mai 


# Speciality 

Numpy C mai bana hua hai pr uske around wrapper banaya gay ajis vajese hum Python mai use krte hai ushe. Fir  isliye C se hume speed millrha hai & comfort humme python ke syntax se millraha.
Numpy ke vajese ML pssible hua python mai 
Numpy ke upar pandas, matplotlib sklearn sbh internally numpy use krte hai.


## Creating Numpy

In [1]:
import numpy as np 

a= np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


## 2D & 3D array

In [2]:
# 2d array of numpy Matrix bhi bolskte 
b = np.array([[9,999,999],[989,90,999]])
print(b)

[[  9 999 999]
 [989  90 999]]


In [3]:
# 3d array 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# different data type
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [5]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

### Np.arange  same as range

In [6]:
a=np.arange(1,10) # just same as range
print(a)

[1 2 3 4 5 6 7 8 9]


### np.arange with reshape

In [7]:
#E.g used fo reshaping matrix vgera bananekeliye 
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
#np.arange(1,11).reshape(5,2)
np.arange(2,11).reshape(3,3)


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
np.arange(1,13).reshape(6,2) # 12 total hai so shape bhi usko vaise hie divide krke dena hai
#row & column mai e.g 4x3 = 12 orelse 3*4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# np.ones 

In [12]:
# np.ones -  bhaut useful hai , yeah use karke on the go numpy array banasakte hai jiske saare items 1 hote hai 

np.ones((3,4))

# Why we use this ? 
# jaha bhi value initialize  karna hoo vahape hum np.ones use karke direct value initialize karsakte hai sidhe 
# so vaha pe ese sidhe  value create karskte just by knowing shape .


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# np.zeros

In [13]:
np.zeros((3,4))
# initialize krneke kaam bhi aata hai yeahbhi 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.random

In [14]:
np.random.random((3,4))
# Yeah random value fill krke dega or initialize krke dega 

array([[0.52483851, 0.62871589, 0.480049  , 0.99822048],
       [0.80326705, 0.55001554, 0.71503143, 0.03175594],
       [0.52142232, 0.62111363, 0.51904006, 0.89191408]])

## -------------------------------------------------------------------------------------------

# np.linspace

In [15]:
#np.linspace(start, end ,total number of numbers that you want)
#E.g
np.linspace(-9,9,10)

# Linspace hamesha Equal distance pe saare point generate karta hai e.g output tum dekh sakte hoo. (Linear separable point generate karta hai in given range e.g plot mai use karskte flow dikhaneko )

array([-9., -7., -5., -3., -1.,  1.,  3.,  5.,  7.,  9.])

#  np.identity - ( Identity Matrix- Identity matrix esa matrix hota hai jiske diagonal 1 hote hai & saare item zero hote hai  )

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ---------------------------------------------------------------------------------------------------

# Numpy Array Attributes 

# ndim - number of dimensions

In [17]:
a1 = np.arange(10) # 1d array vector 
a2= np.arange(12,dtype=float).reshape(3,4) # 2d array matrix
a3 = np.arange(8).reshape(2,2,2) #3d tensor

print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [18]:
# ndim - number of dimensions
# yeah number of dimension batata hai ndarray ka

a1.ndim

1

In [19]:
a2.ndim # matrix - rows & column

2

In [20]:
a3.ndim # as it is 3d array 

3

# Shape

In [21]:
# shape :  yeah batata hai ki har dimension mai kitne item hai 
a1.shape

(10,)

In [22]:
a2.shape # 3 rows & 4 columns

(3, 4)

In [23]:
a3.shape # their are two  2d array of shape 2,2

(2, 2, 2)

# size - yeah batata hai ki number of size kitna hai .

In [24]:
a1.size

10

In [25]:
a2.size

12

In [26]:
a3.size

8

# itemsize - item size yeah batata hai ki memory mai kitna size occupy krrha hai
# basically Byte return karta hai yeah ( 8 bits = 1 byte ) 

In [27]:
a1.itemsize

4

In [28]:
a2.itemsize

8

In [29]:
a3.itemsize

4

# changing datatype 

In [30]:
# data type change bhi krskte hum kisi numpy ka 
# E.g future mai data type aaya smjho tou uska data type chutya jaisa hoo tou isliye 
# data type change krke hum memonry save karsakte hai 
# fir dataset kamm memory khaata hai 
a3.dtype

dtype('int32')

In [31]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operations 

### almost har type ka mathematical operations support karta hai numpy 

In [32]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Scalar Operation & Vector Operations

### Scalar mai 1 single numpy array ko 1 single number se operation krte ho E.g 
### Arithmetic : 

In [33]:
# Multiplication

a1*2 # sbh item 2 se multiply hojayenge 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [34]:
# Addition
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [35]:
# Subtraction 
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [36]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

### Relational:

In [37]:
a2 > 5 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [38]:
a1 >5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
a1 <5 

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [40]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

## Vector Operations 

In [41]:
# vector mai add krdenge hum 2 same shape vale array ko 
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [42]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [43]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

##  Numpy Array Function - har mathmatical operation keliye ek function rahega 

In [44]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[43., 34., 24.],
       [44., 33., 18.],
       [20.,  3., 46.]])

## Max, Min , Sum , Product 

In [45]:
np.max(a1)

46.0

In [46]:
np.min(a1)

3.0

In [47]:
np.sum(a1) # sum of whole item

265.0

In [48]:
np.prod(a1) # multiplication of whole 

2531085511680.0

###   if you wanna know minimum item from the single row of array then do this 
### 0 - Ka matlab column & 
### 1 - ka mtlb row  

In [49]:
# if you wanna know minimum item from the single row of array then do this 
# 0 - Ka matlab column & 
# 1 ka mtlb row 
np.max(a1,axis=1) # maximum value har row ka bataraha

array([43., 44., 46.])

In [50]:
np.max(a1,axis=0) # maximum value yeah har column ka bataraha 

array([44., 34., 46.])

In [51]:
np.min(a1,axis=1) # minimum value of every row 

array([24., 18.,  3.])

In [52]:
np.min(a1,axis=0) # minimum value of every column

array([20.,  3., 18.])

In [53]:
np.sum(a1,axis=1) # har row ka sum dega 

array([101.,  95.,  69.])

In [54]:
np.sum(a1,axis=0) # har column ka sum dega 

array([107.,  70.,  88.])

In [55]:
np.prod(a1,axis=1) # har row ka multiplication deraha

array([35088., 26136.,  2760.])

In [56]:
np.prod(a1,axis=0) # har column ka multiplication deraha

array([37840.,  3366., 19872.])

# -----------------------------------------------------------------------------------------------------

## Statistical Operations 

### Mean - np.mean()

In [57]:
a1 = np.array((1,2,3,4,4,4,999))
np.mean(a1)

145.28571428571428

#### yaha bhi axis = 0 & 1 use krke column & row wise mean nikalata jaaskta hai 


### Median - np.meadian()

In [58]:
np.median(a1)

4.0

### Standard Deviation - np.std()

In [59]:
np.std(a1)

348.529037234946

### Variance - np.var() ( Measure of spread to know how much data is spread ) 

In [60]:
np.var(a1)

121472.48979591837

### ------------------------ Trignometric Function -----------------------

In [61]:
np.sin(a1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.7568025 ,
       -0.7568025 , -0.02646075])

In [62]:
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362, -0.65364362,
       -0.65364362,  0.99964985])

In [63]:
np.tan(a1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128,  1.15782128,
        1.15782128, -0.02647002])

### ------------------------------------------ np.dot() - Dot Product yeah Usefull hai -------------------------------------

### 2 matrixes ke beech ka dot product nikalte hai 
### Eg.
### Ek ka  matrix hai 3,4 & ek ka matrix hai 4,3  so we will check ki dono same hai ki nahi ?
### agar yeah same hai tou result aayega 3,3 

### Dot product mai 1st matrix ka column & 2nd matrix ka row same raha tbhi Dot Product hogga 
### & fir result mai 1st matrix ka row & 2nd matrix ka colum aayega 

In [64]:
# E.g 

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

### Log & Exponents 

In [65]:
np.log(a2)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [66]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

## Round / Floor / Ceil 

### Round : Nearest Integer pe round off karta hai usko exact maanleta hai 

In [67]:
np.round(np.random.random((2,3))*100)

array([[12., 93., 23.],
       [ 3., 58., 12.]])

### Floor: peeche vale values provide krta hai aageh vale nahi  E.g 9.9 hai tou yeah 9 dega

In [68]:
np.floor(np.random.random((2,3))*100)

array([[78., 73., 84.],
       [87., 76., 68.]])

### Ceil:  Ceil aageh value integer deta hai e.g 9.7 hai tou output 10 dega 

In [69]:
np.floor(np.random.random((2,3))*100)

array([[27., 39., 59.],
       [37., 47.,  8.]])

## Indexing & Slicing 

In [70]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a1[0]

0

In [72]:
a2[1,3] # accesing 1st row  3rd column element

7

In [73]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
a3[1,0,1] # 1st index array then 0th row 1st index

10

In [75]:
a3[0,1,0] # 0th index array in that 1st index row & oth column index 

3

In [76]:
a3[0,0,0]

0

In [77]:
a3[1,1,0]

12

## Slicing 

In [78]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a1[2:5]

array([2, 3, 4])

In [80]:
a1[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a2[0]

array([0, 1, 2, 3])

In [83]:
a2[0,:]

array([0, 1, 2, 3])

In [84]:
a2[:,2]

array([ 2,  6, 10])

In [85]:
# 5,6 ,9,10 in a2 access that 

a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [86]:
# 0,3,8,11 access that in a2
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [87]:
# 1,3,9,11 access that in a2
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [88]:
# now accessing 3d array
# row , row, column
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [90]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
a3[0,1,:]

array([3, 4, 5])

In [99]:
#10,13,16
a3[1,0:,1]

array([10, 13, 16])

In [98]:
# 22,23,25,26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [100]:
# 0,2,18,20

a3[0::2,0,0::2]


array([[ 0,  2],
       [18, 20]])

## Iterating loop on numpy array

In [101]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [108]:
# 2d hai so row print hota hai 1 baar mai 
# np.nditer() ishse 2d & 3d array iterate krskte 
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [109]:
# 3d hai so 2d array print hota hai 
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping Function 

### Transpose -> row ko column krdeta hai & column ko row kardeta hai  

In [110]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
a2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [112]:
# another syntax 
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## Ravel - yeah kitne bhi dimension ke array hai usko yeah 1d mai convert kardeta hai 

In [113]:
# E.g converting 2d array in 1d array 
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
# E.g converting 2d array in 1d array 
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking 
iska matlab 2 ya 2 se zyaada numpy arrays ko nhum stackup krskte mtlb jodd sakte hai 
iska shape hamesha same hona chaye 
### use: kahi baar esa hoga ki multiple data source honge e.g  3 jageh se data aarha hai  api se , database se , & ### web scrapping  teeno data similar hai  so humme teeno ko milake analysis krna hoga tou  humm vaha pe stack ### use krke jodd skte sbh data ko  ( Multiple datasources ko joddneka tarika hai ) 

## Horizontal Stacking - yeah aaju baju joddta hai 

In [116]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [117]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [123]:
# doing horizontal stacking 
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## Vertical Stacking - Yeah upar neeche joddega 

In [122]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#  Splitting : just a opposite of stacking... Stacking ka ulta operation hai 
## Use:  iska use jbh 1 datasource se multiple chize hum banarahe hoo 
## e.g 1 clg ka data hai & suppose usmese branch wise data alag krna chahte hoo hum

## Horizontal Splitting  Hsplit  - np.hsplit(   ,yaha pe parts daalo )
#### isme sidhe sidhe katega 
### & equal parts mai hie katega hamesha 

In [125]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [129]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

# Vertical Splitting -  Vsplit  - yaha pe teda katega 

In [130]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [135]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]