# Numpy Tricks 

## np.sort() : Return a sorted copy of an array. 
### np.sort(array_dedo_yaha , axis = , kind = None , order = None )

#### kind - mai koi bhi sorting technique daalskte e.g quicksort , merge sort etc etc 

In [1]:
import numpy as np 

a = np.random.randint(1,100,15)
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 5, 76, 52, 33],
       [75, 97, 97, 42],
       [76,  8,  9, 32],
       [58, 15, 82, 39],
       [13, 87, 70, 23],
       [12, 89, 38, 27]])

In [3]:
np.sort(a)

array([ 9, 12, 25, 30, 36, 38, 53, 68, 69, 73, 80, 82, 92, 95, 97])

In [4]:
b

array([[ 5, 76, 52, 33],
       [75, 97, 97, 42],
       [76,  8,  9, 32],
       [58, 15, 82, 39],
       [13, 87, 70, 23],
       [12, 89, 38, 27]])

In [5]:
# So yeah 2d array hai so Row wise sort krta hai as you can see. 
np.sort(b)

array([[ 5, 33, 52, 76],
       [42, 75, 97, 97],
       [ 8,  9, 32, 76],
       [15, 39, 58, 82],
       [13, 23, 70, 87],
       [12, 27, 38, 89]])

In [6]:
#  1 mtlb row
np.sort(b,axis=0)

array([[ 5,  8,  9, 23],
       [12, 15, 38, 27],
       [13, 76, 52, 32],
       [58, 87, 70, 33],
       [75, 89, 82, 39],
       [76, 97, 97, 42]])

In [7]:
# if descending mai sort krna hoga tou 

np.sort(a)[::-1]

array([97, 95, 92, 82, 80, 73, 69, 68, 53, 38, 36, 30, 25, 12,  9])

# np.append() 

###  The numpy.appends() values along the mentioned axis at the end of the array.

In [8]:
np.append(a,900)

array([ 12,   9,  97,  38,  92,  82,  36,  73,  68,  95,  53,  80,  25,
        30,  69, 900])

In [9]:
b

array([[ 5, 76, 52, 33],
       [75, 97, 97, 42],
       [76,  8,  9, 32],
       [58, 15, 82, 39],
       [13, 87, 70, 23],
       [12, 89, 38, 27]])

In [10]:
# ek existing 2d array mai 1 extra column add krdiya humnne
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 5., 76., 52., 33.,  1.],
       [75., 97., 97., 42.,  1.],
       [76.,  8.,  9., 32.,  1.],
       [58., 15., 82., 39.,  1.],
       [13., 87., 70., 23.,  1.],
       [12., 89., 38., 27.,  1.]])

# np.concatenate()

## numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
# axis - 0 row , 1 - column
np.concatenate((c,d),axis=1) # column concatenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [13]:
# row concatenation
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Np.Unique() - yeah unique value nikalsakte hai array mai se 

### with the help of np.unique(0 method, we can get the unique values from an array 
### as given as parameter in np.unique() method.



In [14]:
x = np.array([1,1,2,2,3,3,4,4,5,5,9,9])

In [15]:
np.unique(x)

array([1, 2, 3, 4, 5, 9])

# np.expand_dims -> dimension expand krneko use krte hai 

### with the help of Numpy.expand_dims() method. we can get the expanded dimensions of an array.


In [16]:
a.shape # -> 1d array hai 

(15,)

In [17]:
np.expand_dims(a,axis=0).shape # - > 1 row 15 column yeha 2d bnngaya hai abh

(1, 15)

In [18]:
np.expand_dims(a,axis=1).shape # ->  15 column & 1 row ka 2d array bnngya 

(15, 1)

### Use of np.expand_dims(): it helps in making row vector & column vector jbh linear algebra padhunga tbh ###  dekhunga 
#### Yeah Function kaafi use full hai 

# ML algorithm  & even DL mai CNN images jbh leta hai tou most of the algos
## ko 1 data nahi chaye hota unhe  Batches of data chaye hote hai or else set of data chaye rehte hai 
## so at that time we use np.expand_dims()


## -----------------------------------------------------------------------------------------------------------------------

# np.where() - The np.where() function returns the indixes of elements in an input array where the given condition is satisfied.

##  np.where(condition, True,False)

In [19]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [20]:
# find all the indices with value greater than 50 

np.where(a>50)

(array([ 2,  4,  5,  7,  8,  9, 10, 11, 14], dtype=int64),)

In [21]:
# Replace all  values greater than > 50 

np.where(a>50,0,a)

## so we replaced all the values that are greater than 50 we replaced it by 0

array([12,  9,  0, 38,  0,  0, 36,  0,  0,  0,  0,  0, 25, 30,  0])

In [22]:
# replace even number with 0 
np.where(a%2==0,0,a)

array([ 0,  9, 97,  0,  0,  0,  0, 73,  0, 95, 53,  0, 25,  0, 69])

# np.argmax() - yeah sbhse maximum element ka index batata hai

## The numpy.argmax() function returns indices of the max element of the array in a particular axis.

## Analysis ke time & all kaam aajata hai 

In [23]:
# code 
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [24]:
np.argmax(a)

2

In [25]:
b

array([[ 5, 76, 52, 33],
       [75, 97, 97, 42],
       [76,  8,  9, 32],
       [58, 15, 82, 39],
       [13, 87, 70, 23],
       [12, 89, 38, 27]])

In [26]:
# so 2d array ka bhi esehie batayega 
np.argmax(b,axis=1) # row wise max element batayega    

array([1, 1, 0, 2, 1, 1], dtype=int64)

In [27]:
np.argmax(b,axis=0) # now column wise max element batayega    

array([2, 1, 1, 1], dtype=int64)

# np.argmin(): yeah sbhse minimum element ka index batata hai 

In [28]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [29]:
np.argmin(a)

1

In [30]:
b

array([[ 5, 76, 52, 33],
       [75, 97, 97, 42],
       [76,  8,  9, 32],
       [58, 15, 82, 39],
       [13, 87, 70, 23],
       [12, 89, 38, 27]])

In [31]:
np.argmin(b,axis=1)# row wise

array([0, 3, 1, 1, 0, 0], dtype=int64)

In [32]:
np.argmin(b,axis=0)# col wise

array([0, 2, 2, 4], dtype=int64)

In [33]:
np.argmin(b)

0

# np.cumsums(): # This is used when we want to complete the cummulative sum of array elements over a given axis.

# cummulative sum matlab - >  har element ko peeche vale element se jbh joddte tou usko cummulative sum bolte hai 

In [34]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [35]:
np.cumsum(a)

array([ 12,  21, 118, 156, 248, 330, 366, 439, 507, 602, 655, 735, 760,
       790, 859], dtype=int32)

In [36]:
b

array([[ 5, 76, 52, 33],
       [75, 97, 97, 42],
       [76,  8,  9, 32],
       [58, 15, 82, 39],
       [13, 87, 70, 23],
       [12, 89, 38, 27]])

In [38]:
np.cumsum(b) #axis specify nahi kiya tou 1d mai convert kardega yeah

array([   5,   81,  133,  166,  241,  338,  435,  477,  553,  561,  570,
        602,  660,  675,  757,  796,  809,  896,  966,  989, 1001, 1090,
       1128, 1155], dtype=int32)

In [40]:
np.cumsum(b,axis=1) # row wise 

array([[  5,  81, 133, 166],
       [ 75, 172, 269, 311],
       [ 76,  84,  93, 125],
       [ 58,  73, 155, 194],
       [ 13, 100, 170, 193],
       [ 12, 101, 139, 166]], dtype=int32)

In [42]:
np.cumsum(b,axis=0) # column wise

array([[  5,  76,  52,  33],
       [ 80, 173, 149,  75],
       [156, 181, 158, 107],
       [214, 196, 240, 146],
       [227, 283, 310, 169],
       [239, 372, 348, 196]], dtype=int32)

# np.cumprod() : yeah cummulative product deta same as np.cumsum hai bss vo add krta hai & yeah Multiply 

In [44]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [45]:
np.cumprod(a)

array([         12,         108,       10476,      398088,    36624096,
       -1291791424,   740148992, -1803698432,  1902558208,   354403328,
        1603507200,  -568442880, -1326170112, -1130397696,  -688029696],
      dtype=int32)

# np.percentile :-  yeahbhi imp hai thoda

## np.percentile() function used to compute the nth percentile of given data (array) 
percentile ka mtlb  suppose kisika 99 percentile aaya hai so mtlb 99 public ushse peeche hai. 

 percentile formula :  p = (n/N) x 100 , n:kitnelog aapse peeche hai & N : total kitnelog hai 

In [46]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [47]:
# 100 percentile mtlb sbhse max vala number 
np.percentile(a,100)

97.0

In [48]:
# 0 percentile mtlb minimum jo sbhse kamm hoo 
np.percentile(a,0)

9.0

In [49]:
np.percentile(a,50)

68.0

In [50]:
np.median(a)

68.0

# np.histogram() acha khasa kaam ka function hai yeabhi 

### it basically gives frequency count 

In [51]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [53]:
np.histogram(a,bins=[0,50,100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

# np.corrcoef : Stats ka hai lyk & yeah batata hai ki  koi bhi 2 Quantitys kitni co-related hai basically relation kaisa hai 

#### Return mai yeah Matrix deta hai 

#### so correlation generally -1 se 1 ke beech mai hota hai 

#### if correlation  0 hai so iska matlb experience & salary mai koi relation nahi hai 
#### if correlation 1 hai so experience & salary both are positively correlated matlab jitna experience badega utna hie salary ka amount bhi badega

#### if correlation -1 hai so isko negatively correlated bollenge iska mtlb ki jitna experience badega utne amount se salary decrease hogga .


In [60]:
salary = np.array([900,9000000,90000,90000000])
experience = np.array([1,3,2,4])

np.corrcoef(salary,experience)

# TPM Transistional Probability Matrix : 

#             salary   experience
#     salary    1        0.82
# experience    0.82      1

array([[1.        , 0.82415611],
       [0.82415611, 1.        ]])

# np.isin(): bhaut saare item search krke dedeta hai 1 array se
With the help of np.isin() method  
ek given array ke andar multiple item search krke dedeta hai 

In [63]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [64]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False])

In [66]:
a[np.isin(a,items)]
# abh yeah jo item mila hai vo dedega humme

array([80, 30])

# np.flip()  - Mirror Image kindoff hai
The np.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.


In [67]:
# Code 
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [69]:
np.flip(a)

array([69, 30, 25, 80, 53, 95, 68, 73, 36, 82, 92, 38, 97,  9, 12])

In [70]:
b

array([[ 5, 76, 52, 33],
       [75, 97, 97, 42],
       [76,  8,  9, 32],
       [58, 15, 82, 39],
       [13, 87, 70, 23],
       [12, 89, 38, 27]])

In [71]:
# flip on 2d 

np.flip(b)
# isme kya hua ki 1 baar column flipping hua then uskebaad Row flipping hua 

array([[27, 38, 89, 12],
       [23, 70, 87, 13],
       [39, 82, 15, 58],
       [32,  9,  8, 76],
       [42, 97, 97, 75],
       [33, 52, 76,  5]])

In [72]:
# if 2d array ka single flipping karana hoo tou axis daaldo bss
np.flip(b,axis=1)

array([[33, 52, 76,  5],
       [42, 97, 97, 75],
       [32,  9,  8, 76],
       [39, 82, 15, 58],
       [23, 70, 87, 13],
       [27, 38, 89, 12]])

In [73]:
np.flip(b,axis=0)

array([[12, 89, 38, 27],
       [13, 87, 70, 23],
       [58, 15, 82, 39],
       [76,  8,  9, 32],
       [75, 97, 97, 42],
       [ 5, 76, 52, 33]])

# np.put() - replace krne mai kaam aajata hai  & Yeah Permanent array mai changes maardeta hai sidhe 
THe np.put() function replaces specific elements of an array with given values of p_array.
Array indexed works on flattened array.

In [74]:
a

array([12,  9, 97, 38, 92, 82, 36, 73, 68, 95, 53, 80, 25, 30, 69])

In [75]:
np.put(a,[0,1],[99,999])

In [76]:
a

array([ 99, 999,  97,  38,  92,  82,  36,  73,  68,  95,  53,  80,  25,
        30,  69])

# np.delete() - 
The np.delete(0 function returns a new array of sub-arrays along with mentioned axis.

In [77]:
a

array([ 99, 999,  97,  38,  92,  82,  36,  73,  68,  95,  53,  80,  25,
        30,  69])

In [91]:
# let's delete multiple items now....
np.delete(a,[3,6,8,10])

array([ 99, 999,  97,  92,  82,  73,  95,  80,  25,  30,  69])

In [87]:
a

array([ 99, 999,  97,  38,  92,  82,  36,  73,  68,  95,  53,  80,  25,
        30,  69])

In [90]:
np.delete(a,3)

array([ 99, 999,  97,  92,  82,  36,  73,  68,  95,  53,  80,  25,  30,
        69])

# Set Functions
iska benefit yeah hai ki iska result hamesha numpy array mai hie millega , set mai nahi millega 

## 1. np.union1d
## 2. np.intersect1d
## 3. np.setdiff1d
## 4. np.setxor1d
## 5. np.in1d

In [97]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([3,4,5,6,7,8,9])


np.union1d(n1,n2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# dono n1, n2 array ke andar ka common element display karlega 

np.intersect1d(n1,n2)

array([3, 4, 5])

In [101]:
# np.setdiff1d(array,differencewith) so 1st normal array dalenge 2nd vala comparision dalenge # hai , nahi hai 

np.setdiff1d(n1,n2) 
# so 1 & 2 dega coz yeah n1 mai hai but n2 mai nahi 

array([1, 2])

In [103]:
# np.setdiff1d(n1,n2) 

np.setdiff1d(n2,n1)

array([6, 7, 8, 9])

In [104]:
# np.setxor1d() - Jo common hoga dono mai vo nikalldega yeah & uncommon return krega bss 

np.setxor1d(n1,n2)

array([1, 2, 6, 7, 8, 9])

In [117]:
# np.in1d(array, elements) - yeah membership operator jaisa hai bss

np.in1d(n1,2)

array([False,  True, False, False, False])

In [112]:
np.in1d(n2,9)

array([False, False, False, False, False, False,  True])

In [116]:
np.in1d(n1,[1,9,2,4,0])

array([ True,  True, False,  True, False])

# np.clip()  - Yeah specified range mai value rkhta hai bss
npclip(array, min= , max=)


In [118]:
a

array([ 99, 999,  97,  38,  92,  82,  36,  73,  68,  95,  53,  80,  25,
        30,  69])

In [123]:
np.clip(a,a_min=50,a_max=99)

array([99, 99, 97, 50, 92, 82, 50, 73, 68, 95, 53, 80, 50, 50, 69])